[[AbstractFFTs]]
deps = ["Compat", "LinearAlgebra"]
git-tree-sha1 = "8d59c3b1463b5e0ad05a3698167f85fac90e184d"
uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c"
version = "0.3.2"

[[AbstractTrees]]
deps = ["Markdown", "Test"]
git-tree-sha1 = "feb8b2c99359901e295443c9d0c7e711604acf39"
uuid = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
version = "0.2.0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BasisFunctions]]
deps = ["AbstractTrees", "DSP", "Domains", "FFTW", "FastGaussQuadrature", "LinearAlgebra", "QuadGK", "RecipesBase", "SpecialFunctions", "StaticArrays"]
path = "/Users/vincentcp/julia/BasisFunctions.jl"
uuid = "8ac202e8-8a12-11e8-0422-2b902fe89c2d"
version = "0.1.0"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "160d5d926e83e0970dd549ad9fe0ac3e8107e83c"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.8"

[[BinaryProvider]]
deps = ["Compat", "Pkg", "SHA"]
git-tree-sha1 = "94dac52c662ca793008fb689e3daf626b6139943"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.3.3"

[[ColorTypes]]
deps = ["FixedPointNumbers", "Random", "Test"]
git-tree-sha1 = "456524c5dc9af774533e4133f9989296053c5bdd"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.7.2"

[[Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "InteractiveUtils", "Printf", "Reexport", "Test"]
git-tree-sha1 = "cec56a50029f40f4c13e4f25bf84964fde31905a"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.9.0"

[[Combinatorics]]
deps = ["Compat", "IterTools", "Polynomials"]
git-tree-sha1 = "60c82fafd63df8a8a2c08b29905c64a75fe8bacd"
uuid = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
version = "0.6.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "eb98811a03884748e0e7fc0ceb6849f3bb727ffd"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "0.70.0"

[[Conda]]
deps = ["BinDeps", "Compat", "JSON", "Libdl", "VersionParsing"]
git-tree-sha1 = "6358e179fb9ad0af5ca9cd4d7c691c413cc121f2"
uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d"
version = "0.8.1"

[[Contour]]
deps = ["LinearAlgebra", "StaticArrays", "Test"]
git-tree-sha1 = "4e244ce551b993b721a6dbbd040b5f3d7cba0f48"
uuid = "d38c429a-6771-53c6-b99e-75d170b6e991"
version = "0.5.0"

[[DSP]]
deps = ["AbstractFFTs", "Compat", "FFTW", "LinearAlgebra", "Polynomials", "Reexport", "SpecialFunctions"]
git-tree-sha1 = "c0f6a5033c7729a3428e0ef6843eb34263c437ca"
uuid = "717857b8-e6f2-59f4-9121-6e50c889abd2"
version = "0.5.0"

[[DataStructures]]
deps = ["InteractiveUtils", "REPL", "Random", "Serialization", "Test"]
git-tree-sha1 = "a591110d3ac12c9b4d0cec163fcf234baed7f5ac"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.10.0"

[[Dates]]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[Domains]]
deps = ["IntervalSets", "LinearAlgebra", "Markdown", "StaticArrays"]
git-tree-sha1 = "a0e618e977dcada064b4e5680a22eabe50efd7b6"
repo-rev = "master"
repo-url = "https://github.com/daanhb/Domains.jl.git"
uuid = "a4a0b8aa-7ac0-11e8-2da9-8385f1ed8077"
version = "0.0.1"

[[FFTW]]
deps = ["AbstractFFTs", "BinaryProvider", "Compat", "Conda", "Libdl", "LinearAlgebra", "Reexport", "Test"]
git-tree-sha1 = "60346335ad3aa60bfbdc358c6d1468bffbcff071"
uuid = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
version = "0.2.3"

[[FastGaussQuadrature]]
deps = ["Compat", "SpecialFunctions", "Test"]
git-tree-sha1 = "1452ac1d6931ad5fb1d058bf6f94c83c965f4ef7"
uuid = "442a2c76-b920-505d-bb47-c5924d526838"
version = "0.3.0"

[[FixedPointNumbers]]
deps = ["Pkg", "Test"]
git-tree-sha1 = "53fae3f45b6782dad91e932d941b0bf862110641"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.5.1"

[[GR]]
deps = ["DelimitedFiles", "Random", "Serialization", "Sockets", "Test"]
git-tree-sha1 = "b0a1d37d216fe143020b5d7d49c4fdc18642f150"
uuid = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
version = "0.31.0"

[[InteractiveUtils]]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[IntervalSets]]
deps = ["Compat"]
git-tree-sha1 = "d488eaaac00c8ea66423773e5a86ac81b9ac03e0"
uuid = "8197267c-284f-5f27-9208-e0e47529a953"
version = "0.2.0"

[[IterTools]]
deps = ["Pkg", "SparseArrays", "Test"]
git-tree-sha1 = "ed0787e62dc46b8d8c7c3db54391d71e0da5fefd"
uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
version = "1.0.0"

[[JSON]]
deps = ["Dates", "Distributed", "Mmap", "Sockets", "Test", "Unicode"]
git-tree-sha1 = "723a515212612b2175095fa5fa55da0bb4c377e5"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.18.0"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Markdown]]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Measures]]
deps = ["Compat"]
git-tree-sha1 = "9cdd05418a7f2f7ce534014285edf01f465d6961"
uuid = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
version = "0.2.0"

[[Missings]]
deps = ["Compat"]
git-tree-sha1 = "866fb034899be6055dcb6cb1a70fbda379bb0b55"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "0.2.10"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[NaNMath]]
git-tree-sha1 = "3b18ebac4cc5f22fe5af9b4aa63210ae4495507a"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.1"

[[Pkg]]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[PlotThemes]]
deps = ["PlotUtils", "Requires", "Test"]
git-tree-sha1 = "f3afd2d58e1f6ac9be2cea46e4a9083ccc1d990b"
uuid = "ccf2f8ad-2431-5c83-bf29-c5338b663b6a"
version = "0.3.0"

[[PlotUtils]]
deps = ["Colors", "Dates", "Printf", "Reexport", "Test"]
git-tree-sha1 = "99c6f7f9111d49209cd5859f8fc407bc030defad"
uuid = "995b91a9-d308-5afd-9ec6-746e21dbc043"
version = "0.5.0"

[[Plots]]
deps = ["Contour", "FixedPointNumbers", "GR", "JSON", "Measures", "NaNMath", "PlotThemes", "PlotUtils", "RecipesBase", "Reexport", "Requires", "Showoff", "StaticArrays", "StatsBase"]
git-tree-sha1 = "a89a0fc4b7b1973944d4617f00bb93ec37301bb3"
uuid = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
version = "0.17.3"

[[Polynomials]]
deps = ["Compat"]
git-tree-sha1 = "23d095b4c1ecbacd78bb0eea6b85d6e0872ce3bd"
uuid = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
version = "0.4.0"

[[Printf]]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[QuadGK]]
deps = ["DataStructures", "LinearAlgebra", "Test"]
git-tree-sha1 = "d136ea5b320aad2b1a8c3196e642c2282e601660"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "2.0.0"

[[REPL]]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[RecipesBase]]
deps = ["Random", "Test"]
git-tree-sha1 = "298e774bc0fd26b7011358fc9ff0223b4e81aaa6"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "0.4.0"

[[Reexport]]
git-tree-sha1 = "caba582b2e9ef39b9cfff911aa13c5ca1b9a9896"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.1.0"

[[Requires]]
deps = ["Test"]
git-tree-sha1 = "f6fbf4ba64d295e146e49e021207993b6b48c7d1"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "0.5.2"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Showoff]]
deps = ["Compat"]
git-tree-sha1 = "9cb3f3bc5819a5142706cd185d76801c7d292809"
uuid = "992d4aef-0814-514b-bc4d-f2e9a6c4116f"
version = "0.2.0"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SortingAlgorithms]]
deps = ["DataStructures", "Random", "Test"]
git-tree-sha1 = "70840f1a93da48bcc952e71b600f598532372eb0"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "0.3.0"

[[SparseArrays]]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SpecialFunctions]]
deps = ["BinDeps", "BinaryProvider", "Compat", "Libdl"]
git-tree-sha1 = "1cf00baba50536d254f02082c90b98d6e4e1f968"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "0.6.0"

[[StaticArrays]]
deps = ["InteractiveUtils", "LinearAlgebra", "Random", "Statistics", "Test"]
git-tree-sha1 = "d998a83bc2cd507e12b08203e7523f2e60ac9ee6"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.8.2"

[[Statistics]]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[StatsBase]]
deps = ["DataStructures", "LinearAlgebra", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "Test"]
git-tree-sha1 = "515d9c751bc96f9680a2a19f76395ae8ac06a8f5"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.24.0"

[[Test]]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[URIParser]]
deps = ["Compat", "Unicode"]
git-tree-sha1 = "0f9c5e2d14e03fbd00696f9394e288bdd5adacbc"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.3.1"

[[UUIDs]]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[VersionParsing]]
deps = ["Compat"]
git-tree-sha1 = "e8524bb636735227fd9d750dfa81f98db8bc5b0c"
uuid = "81def892-9a0e-5fdd-b105-ffc91e053289"
version = "1.1.1"
