[[AbstractFFTs]]
deps = ["Compat", "LinearAlgebra"]
git-tree-sha1 = "8d59c3b1463b5e0ad05a3698167f85fac90e184d"
uuid = "621f4979-c628-5d54-868e-fcf4e3e8185c"
version = "0.3.2"

[[AbstractTrees]]
deps = ["Markdown", "Test"]
git-tree-sha1 = "feb8b2c99359901e295443c9d0c7e711604acf39"
uuid = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
version = "0.2.0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BasisFunctions]]
deps = ["AbstractTrees", "DSP", "Domains", "FFTW", "FastGaussQuadrature", "LinearAlgebra", "QuadGK", "RecipesBase", "SpecialFunctions", "SpecialMatrices", "StaticArrays"]
git-tree-sha1 = "ccca770764f84bf447522f3738c998fff54bb88c"
repo-rev = "julia-0.7"
repo-url = "https://github.com/daanhb/BasisFunctions.jl.git"
uuid = "8ac202e8-8a12-11e8-0422-2b902fe89c2d"
version = "0.1.0"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "160d5d926e83e0970dd549ad9fe0ac3e8107e83c"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.8"

[[BinaryProvider]]
deps = ["Compat", "Pkg", "SHA"]
git-tree-sha1 = "94dac52c662ca793008fb689e3daf626b6139943"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.3.3"

[[Combinatorics]]
deps = ["Compat", "IterTools", "Polynomials"]
git-tree-sha1 = "60c82fafd63df8a8a2c08b29905c64a75fe8bacd"
uuid = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
version = "0.6.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "eb98811a03884748e0e7fc0ceb6849f3bb727ffd"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "0.70.0"

[[Conda]]
deps = ["BinDeps", "Compat", "JSON", "Libdl", "VersionParsing"]
git-tree-sha1 = "6358e179fb9ad0af5ca9cd4d7c691c413cc121f2"
uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d"
version = "0.8.1"

[[DSP]]
deps = ["AbstractFFTs", "Compat", "FFTW", "LinearAlgebra", "Polynomials", "Reexport", "SpecialFunctions"]
git-tree-sha1 = "c0f6a5033c7729a3428e0ef6843eb34263c437ca"
uuid = "717857b8-e6f2-59f4-9121-6e50c889abd2"
version = "0.5.0"

[[DataStructures]]
deps = ["InteractiveUtils", "REPL", "Random", "Serialization", "Test"]
git-tree-sha1 = "ef6f313c82fd80ab75ab3f784353b6c65ebcaacf"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.9.0"

[[Dates]]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[Domains]]
deps = ["IntervalSets", "LinearAlgebra", "Markdown", "StaticArrays"]
git-tree-sha1 = "a0e618e977dcada064b4e5680a22eabe50efd7b6"
repo-rev = "master"
repo-url = "https://github.com/daanhb/Domains.jl.git"
uuid = "a4a0b8aa-7ac0-11e8-2da9-8385f1ed8077"
version = "0.0.1"

[[FFTW]]
deps = ["AbstractFFTs", "BinaryProvider", "Compat", "Conda", "Libdl", "LinearAlgebra", "Reexport", "Test"]
git-tree-sha1 = "60346335ad3aa60bfbdc358c6d1468bffbcff071"
uuid = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
version = "0.2.3"

[[FastGaussQuadrature]]
deps = ["Compat", "SpecialFunctions", "Test"]
git-tree-sha1 = "1452ac1d6931ad5fb1d058bf6f94c83c965f4ef7"
uuid = "442a2c76-b920-505d-bb47-c5924d526838"
version = "0.3.0"

[[GR]]
deps = ["DelimitedFiles", "Random", "Serialization", "Sockets", "Test"]
git-tree-sha1 = "b0a1d37d216fe143020b5d7d49c4fdc18642f150"
uuid = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
version = "0.31.0"

[[InteractiveUtils]]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[IntervalSets]]
deps = ["Compat"]
git-tree-sha1 = "d488eaaac00c8ea66423773e5a86ac81b9ac03e0"
uuid = "8197267c-284f-5f27-9208-e0e47529a953"
version = "0.2.0"

[[IterTools]]
deps = ["Pkg", "SparseArrays", "Test"]
git-tree-sha1 = "ed0787e62dc46b8d8c7c3db54391d71e0da5fefd"
uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
version = "1.0.0"

[[JSON]]
deps = ["Dates", "Distributed", "Mmap", "Sockets", "Test", "Unicode"]
git-tree-sha1 = "723a515212612b2175095fa5fa55da0bb4c377e5"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.18.0"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Markdown]]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[Pkg]]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Polynomials]]
deps = ["Compat"]
git-tree-sha1 = "23d095b4c1ecbacd78bb0eea6b85d6e0872ce3bd"
uuid = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
version = "0.4.0"

[[Printf]]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[QuadGK]]
deps = ["DataStructures", "LinearAlgebra", "Test"]
git-tree-sha1 = "d136ea5b320aad2b1a8c3196e642c2282e601660"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "2.0.0"

[[REPL]]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[RecipesBase]]
deps = ["Random", "Test"]
git-tree-sha1 = "298e774bc0fd26b7011358fc9ff0223b4e81aaa6"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "0.4.0"

[[Reexport]]
git-tree-sha1 = "caba582b2e9ef39b9cfff911aa13c5ca1b9a9896"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.1.0"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SpecialFunctions]]
deps = ["BinDeps", "BinaryProvider", "Compat", "Libdl"]
git-tree-sha1 = "1cf00baba50536d254f02082c90b98d6e4e1f968"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "0.6.0"

[[SpecialMatrices]]
git-tree-sha1 = "91992ec5d705195fe46caf949f002daf84dfde34"
uuid = "928aab9d-ef52-54ac-8ca1-acd7ca42c160"
version = "0.1.3"

[[StaticArrays]]
deps = ["InteractiveUtils", "LinearAlgebra", "Random", "Statistics", "Test"]
git-tree-sha1 = "d998a83bc2cd507e12b08203e7523f2e60ac9ee6"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.8.2"

[[Statistics]]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[Test]]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[URIParser]]
deps = ["Compat", "Unicode"]
git-tree-sha1 = "0f9c5e2d14e03fbd00696f9394e288bdd5adacbc"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.3.1"

[[UUIDs]]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[VersionParsing]]
deps = ["Compat"]
git-tree-sha1 = "e8524bb636735227fd9d750dfa81f98db8bc5b0c"
uuid = "81def892-9a0e-5fdd-b105-ffc91e053289"
version = "1.1.1"
